### ISSUE TITLE
Ctype spectrum display affected by stack edit

### ISSUE THREAD

**Issue by Maticzpl** [krawthekrow/TPT-Subframe-Mod#2]
![QGdbrN6MnV](https://user-images.githubusercontent.com/27724912/126970871-08a17f5f-48d2-4153-be60-ccfdff005e2c.gif)

**Comment by krawthekrow** [comment]
Thanks for reporting! Fixed in 667a9a2c6133395fe7d396d2bdab8a3c109ffec4, pending next release.
